---
title: "In-Class_Ex7"
format: html
date-modified: "last-modified"
execute:  
  warning: false
  freeze: true
  message: false 
  eval: true 
  echo: true 
  fig-retine: 3
date: "`r Sys.Date()`" 
---

## Loading Packages 

Package: sp is noy included in the Hands-on Ex.7

gdal: longer in crane, not commonly use now

```{r}
pacman::p_load(rgdal, sp, spdep, tmap, sf, ClustGeo, 
               ggpubr, cluster, factoextra, NbClust,
               heatmaply, corrplot, psych, tidyverse, GGally)
```

```{r}
shan_sf <- st_read(dsn = "data/geospatial",                    
                   layer = "myanmar_township_boundaries") %>%   
  filter (ST %in% c("Shan (East)", "Shan (North)",                     
                    "Shan (South)")) %>%   select(c(2:7))

```

```{r}
ict <- read_csv("data/aspatial/Shan-ICT.csv")
```

```{r}
# understand the type of shan_sf
class(shan_sf)
```

```{r}
shan_sf
```

```{r}
# look at the range of the data 
summary(ict)
```

```{r}
ict_derived <- ict %>%
  mutate(`RADIO_PR` = `Radio`/`Total households`*1000) %>%
  mutate(`TV_PR` = `Television`/`Total households`*1000) %>%
  mutate(`LLPHONE_PR` = `Land line phone`/`Total households`*1000) %>%
  mutate(`MPHONE_PR` = `Mobile phone`/`Total households`*1000) %>%
  mutate(`COMPUTER_PR` = `Computer`/`Total households`*1000) %>%
  mutate(`INTERNET_PR` = `Internet at home`/`Total households`*1000) %>%
  rename(`DT_PCODE` =`District Pcode`,`DT`=`District Name`,
         `TS_PCODE`=`Township Pcode`, `TS`=`Township Name`,
         `TT_HOUSEHOLDS`=`Total households`,
         `RADIO`=`Radio`, `TV`=`Television`, 
         `LLPHONE`=`Land line phone`, `MPHONE`=`Mobile phone`,
         `COMPUTER`=`Computer`, `INTERNET`=`Internet at home`) 
```

```{r}
summary(ict_derived)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
