project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
          - text: "Hands-on Excercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Excercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Excercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Excercise 4"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
          - text: "Hands-on Excercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Excercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Excercise 7"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "Hands-on Excercise 8"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
         
          
            
      - text: "In-Class Exercise"
        menu: 
          - text: "In-Class Exercise 2"
            href: "In-Class_Ex/In-Class_Ex2/In-Class_Ex2.html"
          - text: "In-Class Exercise 3"
            href: "In-Class_Ex/In-Class_Ex3/In-Class_Ex3.html"
          - text: "In-Class Exercise 3-NKDE"
            href: "In-Class_Ex/In-Class_Ex3/In-Class_Ex3-NKDE.html"
          - text: "In-Class Exercise 4"
            href: "In-Class_Ex/In-Class_Ex4/In-Class_Ex4.html"
          - text: "In-Class Exercise 5"
            href: "In-Class_Ex/In-Class_Ex5/In-Class_Ex5.html"
       
       
      - text: "Take-home Exercise"
        menu: 
          - text: "Data Preparation for Take-home_Ex01"
            href: "Take-home_Ex/Take-home_Ex1/Data_Prep_Take-home_Ex1.html"
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex1/Take-home_Ex1-KDE.html"
          - text: "Data Preparation for Take-home_Ex02"
            href: "Take-home_Ex/Take-home_Ex2/Data_Prep_Take-home_Ex2.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html"
      
            
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

