---
title: "In-Class Ex11"
format: html
date-modified: "last-modified"
execute:  
  warning: false
  freeze: true
  message: false 
  eval: true 
  echo: true 
  fig-retine: 3
date: "`r Sys.Date()`"
---

```{r}
pacman::p_load(tmap, sf, DT, stplanr, tidyverse)
```

```{r}
odbus <- read_csv("data/aspatial/origin_destination_bus_202210.csv")

```

```{r}
glimpse(odbus)
```

```{r}
odbus$ORIGIN_PT_CODE <- as.factor(odbus$ORIGIN_PT_CODE) 
odbus$DESTINATION_PT_CODE <- as.factor(odbus$DESTINATION_PT_CODE) 
```

```{r}
 odbus6_9 <- odbus %>%   filter(DAY_TYPE == "WEEKDAY") %>%   
   filter(TIME_PER_HOUR >= 6 & TIME_PER_HOUR <= 9) %>%   
   group_by(ORIGIN_PT_CODE, DESTINATION_PT_CODE) %>%   
   summarise(TRIPS = sum(TOTAL_TRIPS))
```

```{r}
busstop <- st_read(dsn = "data/geospatial",                    
                   layer = "BusStop") %>%   st_transform(crs = 3414)

```

```{r}
mpsz <- st_read(dsn = "data/geospatial",                    
                layer = "MPSZ-2019") %>%   st_transform(crs = 3414)
```

```{r}
mpsz
```

```{r}
mpsz <- write_rds(mpsz, "data/rds/mpsz.rds")
```

```{r}
 busstop_mpsz <- st_intersection(busstop, mpsz) %>%   
   select(BUS_STOP_N, SUBZONE_C) %>%   
   st_drop_geometry()
```

```{r}
write_rds(busstop_mpsz, "data/rds/busstop_mpsz.rds")  

```

```{r}
od_data <- left_join(odbus6_9 , busstop_mpsz,
                    by = c("ORIGIN_PT_CODE" = "BUS_STOP_N")) %>%   
                    rename(ORIGIN_BS = ORIGIN_PT_CODE, ORIGIN_SZ = SUBZONE_C, 
                    DESTIN_BS = DESTINATION_PT_CODE)
```

```{r}
duplicate <- od_data %>%   
  group_by_all() %>%   
  filter(n()>1) %>%   
  ungroup()
```

```{r}
od_data <- unique(od_data)

```

```{r}
od_data <- left_join(od_data , busstop_mpsz,            
                     by = c("DESTIN_BS" = "BUS_STOP_N")) 
   

```

```{r}
duplicate <- od_data %>%   
  group_by_all() %>%   
  filter(n()>1) %>%   
  ungroup()
```

```{r}
od_data <- unique(od_data)
```

```{r} od_data <- od_data %>%   rename(DESTIN_SZ = SUBZONE_C) %>%   drop_na() %>%   group_by(ORIGIN_SZ, DESTIN_SZ) %>%   summarise(MORNING_PEAK = sum(TRIPS))}
   
```

```{r}
write_rds(od_data, "data/rds/od_data_fii.rds.rds")
```

```{r}
od_data_fii <- read_rds("data/rds/od_data_fii.rds.rds")
```

```{r}
#| eval: false 
od_data_fij <- od_data[od_data$ORIGIN_SZ!=od_data$DESTIN_SZ,]
```

```{r} #| eval: false}
write_rds(od_data_fij, "data/rds/od_data_fij.rds")
```

```{r}
od_data_fij <- read_rds("data/rds/od_data_fij.rds")
```

```{r}
#| eval: false 
flowLine <- od2line(flow = od_data_fij,                      
                    zones = mpsz,                     
                    zone_code = "SUBZONE_C")
```

```{r}
#| eval: false 
write_rds(flowLine, "data/rds/flowLine.rds")
```

```{r}
flowLine <- read_rds("data/rds/flowLine.rds")
```

```{r}
tm_shape(mpsz) +
  tm_polygons() + 
  flowLine %>%   
  tm_shape() +   
  tm_lines(lwd = "MORNING_PEAK", 
           style = "quantile", 
           scale = c(0.1, 1, 3, 5, 7, 10),           
           n = 6,            
           alpha = 0.3)
```

```{r}
```
